### ISSUE TITLE
Scene: Usability improves

### ISSUE THREAD

**Issue by avuorinen** [Acerba/Acerba#3]
# Missing Methods (Entity)
* SetParent

# Other
* Logic Issues?

**Comment by Elbereth9001** [comment]
# Added Methods (Entity)
* SetParent

# Other
* Logic Issues?
* Add nullptr checks to Entity member functions?

**Comment by avuorinen** [comment]
Check usability problems if there is any and "logic issues?" part can be ignored for now, I will do some testing first for that.
