### ISSUE TITLE
Entity: BaseComponent

### ISSUE THREAD

**Issue by avuorinen** [Acerba/Acerba#8]
# Concept
BaseComponent should contains most used entity features.
(This doesn't mean that old components needs to inheritance BaseComponent, that is **optional**)
* Entity
* Transform
* etc.

```c++
class BaseComponent
{
public:

   BaseComponent(Entity& entity); // EntityHandle*
 
    const Entity* entity;
    const Transform* transform;
    // etc.
};
```

**Comment by Elbereth9001** [comment]
Added basic functionality.
